version: '3.8'

services:
  terp-network:
    build:
      context: .
      dockerfile: Dockerfile
    image: terpnetwork/terp-network:latest
    container_name: terp-network
    ports:
      - "8080:80"
    restart: unless-stopped
