import TwoColumnLayout from "components/layout/twoColumnLayout"
import Head from 'next/head';
import {
  Box,
  Divider,
  Grid,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,
  useColorModeValue,
} from '@chakra-ui/react';

const IBCBridgePage = () => {
  return (
    <div  className="two-column-layout">
    <TwoColumnLayout/>
    <Container maxW="5xl" py={10}>
      <Head>
        <title>Create Cosmos App</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box textAlign="center">
        <Heading
          as="h1"
          fontSize={{ base: '3xl', sm: '4xl', md: '5xl' }}
          fontWeight="extrabold"
          mb={3}
        >
          IBC Transfer
        </Heading>
        
      
      </Box>
     
   
      
    </Container>

    </div>
  )
}


export default IBCBridgePage;