import Head from 'next/head';
import {
  Box,
  Divider,
  Grid,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,
  useColorModeValue,
} from '@chakra-ui/react';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import {
  Product,
  Dependency,
  WalletSection,
  StakingSection,
} from '../components';
import { defaultChainName, dependencies, products } from '../config';

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <Container maxW="5xl"  py={10}>   
      <Head>
        <title>Terp Network Staking </title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="end" mb={4}>
        <Button variant="outline" px={0} onClick={toggleColorMode}>
          <Icon
            as={colorMode === 'light' ? BsFillMoonStarsFill : BsFillSunFill}
          />
        </Button>
      </Flex>
     
      <WalletSection isMultiChain={false} />
      <Divider />
      <StakingSection chainName={defaultChainName} />
      
      
      <Box mb={3}>
        <Divider />
      </Box>
      <Container py={20}>
      <Stack
        isInline={true}
        spacing={1}
        justifyContent="center"
        opacity={0.5}
        fontSize="sm"
      >
      <Text>Built </Text>
        <Text>With </Text>
        <Link
          href="https://github.com/cosmology-tech/create-cosmos-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Cosmology
        </Link>
        </Stack>
        </Container>
        </Container>
  );
}
